# Generated by Django 5.0.4 on 2024-04-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('taker', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=1024)),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
