# Generated by Django 5.0.4 on 2024-04-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_person_profession_delete_note_person_fk_profession'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='profession',
            table='profession',
        ),
    ]
